{% set version = "5.15.15" %}
package:
  name: qt-wayland
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/qtwayland-everywhere-opensource-src-{{ version }}.tar.xz
  sha256: bd1b577ec2311c0f615ca4a21aeb108a0b1b5e112c94191ff709cec814599b51

build:
  skip: true   # [not linux]
  number: 0
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt-wayland', max_pin='x.x') }}

requirements:
  build:
    - perl
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - qt-main  {{ version }}             # [build_platform != target_platform]
    - wayland                            # [build_platform != target_platform]
    - libgl-devel                        # [build_platform != target_platform]
    - libegl-devel                       # [build_platform != target_platform]
    - libdrm                             # [build_platform != target_platform]
  host:
    - qt-main  {{ version }}
    - wayland
    - libgl-devel
    - libegl-devel
    - libdrm
    - fontconfig
    - freetype
    - zlib
    - glib
  run:
    - libxkbcommon

test:
  commands:
    {% set qt_libs = ["WaylandClient", "WaylandCompositor"] %}
    {% for each_qt_lib in qt_libs %}
    - test -d $PREFIX/include/qt/Qt{{ each_qt_lib }}  # [unix]
    - test -f $PREFIX/lib/libQt5{{ each_qt_lib }}${SHLIB_EXT}  # [unix]
    {% endfor %}

about:
  home: http://qt-project.org
  license: LGPL-3.0-only
  license_file:
    -  LICENSE.FDL
    -  LICENSE.GPL2
    -  LICENSE.GPL3
    -  LICENSE.GPL3-EXCEPT
    -  LICENSE.LGPL3
  summary: QtWayland module
  description: |
    The QtWayland module consists of two parts.

    Wayland platform plugin --
        Enables Qt applications to be run as Wayland clients.

    QtWaylandCompositor API --
        Enables the creation of Wayland compositors using Qt and QtQuick.
  doc_url: https://wiki.qt.io/QtWayland
  dev_url: https://github.com/qt/qtwayland/tree/5.15

extra:
  feedstock-name: qt-wayland
  recipe-maintainers:
    - hmaarrfk
    # qt-main added to help in case of any critical fixes or routine upgrades
    - conda-forge/qt-main
