os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  abi_migration_branches:
  - qt6
provider:
  linux: github_actions
  osx: github_actions
  osx_arm64: github_actions
  win: github_actions
build_platform:
  osx_arm64: osx_arm64
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le